// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BorrowBook(ctx context.Context, arg BorrowBookParams) (BorrowedBook, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBook(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetActiveBorrowByBook(ctx context.Context, bookID int32) (BorrowedBook, error)
	GetBook(ctx context.Context, id int32) (Book, error)
	GetBookForUpdate(ctx context.Context, id int32) (Book, error)
	GetOverdueBooks(ctx context.Context) ([]GetOverdueBooksRow, error)
	GetUser(ctx context.Context, id int32) (User, error)
	GetUserBorrowHistory(ctx context.Context, userID int32) ([]GetUserBorrowHistoryRow, error)
	GetUserBorrowedBooks(ctx context.Context, userID int32) ([]GetUserBorrowedBooksRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListBooks(ctx context.Context) ([]Book, error)
	ListUsers(ctx context.Context) ([]User, error)
	ReturnBook(ctx context.Context, arg ReturnBookParams) (BorrowedBook, error)
	SearchBooksByAuthor(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error)
	SearchBooksByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
	UpdateBookAvailability(ctx context.Context, arg UpdateBookAvailabilityParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
