// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: books.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBook = `-- name: CreateBook :one
INSERT INTO books (title, author, description, year_of_publication)
VALUES ($1, $2, $3, $4)
RETURNING id, title, author, description, year_of_publication, created_at, updated_at, available
`

type CreateBookParams struct {
	Title             string      `json:"title"`
	Author            string      `json:"author"`
	Description       pgtype.Text `json:"description"`
	YearOfPublication pgtype.Int4 `json:"year_of_publication"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, createBook,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.YearOfPublication,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.YearOfPublication,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Available,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :exec
DELETE FROM books
WHERE id = $1
`

func (q *Queries) DeleteBook(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteBook, id)
	return err
}

const getBook = `-- name: GetBook :one
SELECT id, title, author, description, year_of_publication, created_at, updated_at, available FROM books
WHERE id = $1
`

func (q *Queries) GetBook(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.YearOfPublication,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Available,
	)
	return i, err
}

const getBookForUpdate = `-- name: GetBookForUpdate :one
SELECT id, title, author, description, year_of_publication, created_at, updated_at, available FROM books
WHERE id = $1
FOR UPDATE
`

func (q *Queries) GetBookForUpdate(ctx context.Context, id int32) (Book, error) {
	row := q.db.QueryRow(ctx, getBookForUpdate, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.YearOfPublication,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Available,
	)
	return i, err
}

const listBooks = `-- name: ListBooks :many
SELECT id, title, author, description, year_of_publication, created_at, updated_at, available FROM books
ORDER BY id
`

func (q *Queries) ListBooks(ctx context.Context) ([]Book, error) {
	rows, err := q.db.Query(ctx, listBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.YearOfPublication,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksByAuthor = `-- name: SearchBooksByAuthor :many
SELECT id, title, author, description, year_of_publication, created_at, updated_at, available FROM books
WHERE author ILIKE '%' || $1 || '%'
ORDER BY author, title
`

func (q *Queries) SearchBooksByAuthor(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooksByAuthor, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.YearOfPublication,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBooksByTitle = `-- name: SearchBooksByTitle :many
SELECT id, title, author, description, year_of_publication, created_at, updated_at, available FROM books
WHERE title ILIKE '%' || $1 || '%'
ORDER BY title
`

func (q *Queries) SearchBooksByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error) {
	rows, err := q.db.Query(ctx, searchBooksByTitle, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.YearOfPublication,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBook = `-- name: UpdateBook :one
UPDATE books
SET title = $2, author = $3, description = $4, year_of_publication = $5, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, title, author, description, year_of_publication, created_at, updated_at, available
`

type UpdateBookParams struct {
	ID                int32       `json:"id"`
	Title             string      `json:"title"`
	Author            string      `json:"author"`
	Description       pgtype.Text `json:"description"`
	YearOfPublication pgtype.Int4 `json:"year_of_publication"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRow(ctx, updateBook,
		arg.ID,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.YearOfPublication,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.YearOfPublication,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Available,
	)
	return i, err
}
