// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: borrowed_books.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const borrowBook = `-- name: BorrowBook :one
INSERT INTO borrowed_books (book_id, user_id, due_date)
VALUES ($1, $2, $3)
RETURNING id, book_id, user_id, borrowed_at, due_date, returned_at
`

type BorrowBookParams struct {
	BookID  int32            `json:"book_id"`
	UserID  int32            `json:"user_id"`
	DueDate pgtype.Timestamp `json:"due_date"`
}

func (q *Queries) BorrowBook(ctx context.Context, arg BorrowBookParams) (BorrowedBook, error) {
	row := q.db.QueryRow(ctx, borrowBook, arg.BookID, arg.UserID, arg.DueDate)
	var i BorrowedBook
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.BorrowedAt,
		&i.DueDate,
		&i.ReturnedAt,
	)
	return i, err
}

const getActiveBorrowByBook = `-- name: GetActiveBorrowByBook :one
SELECT id, book_id, user_id, borrowed_at, due_date, returned_at FROM borrowed_books
WHERE book_id = $1 AND returned_at IS NULL
LIMIT 1
`

func (q *Queries) GetActiveBorrowByBook(ctx context.Context, bookID int32) (BorrowedBook, error) {
	row := q.db.QueryRow(ctx, getActiveBorrowByBook, bookID)
	var i BorrowedBook
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.BorrowedAt,
		&i.DueDate,
		&i.ReturnedAt,
	)
	return i, err
}

const getOverdueBooks = `-- name: GetOverdueBooks :many
SELECT bb.id, bb.book_id, bb.user_id, bb.borrowed_at, bb.due_date, bb.returned_at, b.title, b.author, u.name, u.email
FROM borrowed_books bb
         JOIN books b ON bb.book_id = b.id
         JOIN users u ON bb.user_id = u.id
WHERE bb.returned_at IS NULL AND bb.due_date < CURRENT_TIMESTAMP
ORDER BY bb.due_date ASC
`

type GetOverdueBooksRow struct {
	ID         int32            `json:"id"`
	BookID     int32            `json:"book_id"`
	UserID     int32            `json:"user_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	DueDate    pgtype.Timestamp `json:"due_date"`
	ReturnedAt pgtype.Timestamp `json:"returned_at"`
	Title      string           `json:"title"`
	Author     string           `json:"author"`
	Name       string           `json:"name"`
	Email      string           `json:"email"`
}

func (q *Queries) GetOverdueBooks(ctx context.Context) ([]GetOverdueBooksRow, error) {
	rows, err := q.db.Query(ctx, getOverdueBooks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverdueBooksRow
	for rows.Next() {
		var i GetOverdueBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.BorrowedAt,
			&i.DueDate,
			&i.ReturnedAt,
			&i.Title,
			&i.Author,
			&i.Name,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBorrowHistory = `-- name: GetUserBorrowHistory :many
SELECT bb.id, bb.book_id, bb.user_id, bb.borrowed_at, bb.due_date, bb.returned_at, b.title, b.author
FROM borrowed_books bb
         JOIN books b ON bb.book_id = b.id
WHERE bb.user_id = $1
ORDER BY bb.borrowed_at DESC
`

type GetUserBorrowHistoryRow struct {
	ID         int32            `json:"id"`
	BookID     int32            `json:"book_id"`
	UserID     int32            `json:"user_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	DueDate    pgtype.Timestamp `json:"due_date"`
	ReturnedAt pgtype.Timestamp `json:"returned_at"`
	Title      string           `json:"title"`
	Author     string           `json:"author"`
}

func (q *Queries) GetUserBorrowHistory(ctx context.Context, userID int32) ([]GetUserBorrowHistoryRow, error) {
	rows, err := q.db.Query(ctx, getUserBorrowHistory, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBorrowHistoryRow
	for rows.Next() {
		var i GetUserBorrowHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.BorrowedAt,
			&i.DueDate,
			&i.ReturnedAt,
			&i.Title,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserBorrowedBooks = `-- name: GetUserBorrowedBooks :many
SELECT bb.id, bb.book_id, bb.user_id, bb.borrowed_at, bb.due_date, bb.returned_at, b.title, b.author
FROM borrowed_books bb
         JOIN books b ON bb.book_id = b.id
WHERE bb.user_id = $1 AND bb.returned_at IS NULL
ORDER BY bb.borrowed_at DESC
`

type GetUserBorrowedBooksRow struct {
	ID         int32            `json:"id"`
	BookID     int32            `json:"book_id"`
	UserID     int32            `json:"user_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	DueDate    pgtype.Timestamp `json:"due_date"`
	ReturnedAt pgtype.Timestamp `json:"returned_at"`
	Title      string           `json:"title"`
	Author     string           `json:"author"`
}

func (q *Queries) GetUserBorrowedBooks(ctx context.Context, userID int32) ([]GetUserBorrowedBooksRow, error) {
	rows, err := q.db.Query(ctx, getUserBorrowedBooks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserBorrowedBooksRow
	for rows.Next() {
		var i GetUserBorrowedBooksRow
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.UserID,
			&i.BorrowedAt,
			&i.DueDate,
			&i.ReturnedAt,
			&i.Title,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnBook = `-- name: ReturnBook :one
UPDATE borrowed_books
SET returned_at = CURRENT_TIMESTAMP
WHERE book_id = $1 AND user_id = $2 AND returned_at IS NULL
RETURNING id, book_id, user_id, borrowed_at, due_date, returned_at
`

type ReturnBookParams struct {
	BookID int32 `json:"book_id"`
	UserID int32 `json:"user_id"`
}

func (q *Queries) ReturnBook(ctx context.Context, arg ReturnBookParams) (BorrowedBook, error) {
	row := q.db.QueryRow(ctx, returnBook, arg.BookID, arg.UserID)
	var i BorrowedBook
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.UserID,
		&i.BorrowedAt,
		&i.DueDate,
		&i.ReturnedAt,
	)
	return i, err
}

const updateBookAvailability = `-- name: UpdateBookAvailability :exec
UPDATE books
SET available = $2
WHERE id = $1
`

type UpdateBookAvailabilityParams struct {
	ID        int32       `json:"id"`
	Available pgtype.Bool `json:"available"`
}

func (q *Queries) UpdateBookAvailability(ctx context.Context, arg UpdateBookAvailabilityParams) error {
	_, err := q.db.Exec(ctx, updateBookAvailability, arg.ID, arg.Available)
	return err
}
