apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: bookstore
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  POSTGRES_DB: gobooksnew
  DATABASE_URL: "postgres://postgres:password@postgres-service:5432/gobooksnew?sslmode=disable"

