// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	ID                int32            `json:"id"`
	Title             string           `json:"title"`
	Author            string           `json:"author"`
	Description       pgtype.Text      `json:"description"`
	YearOfPublication pgtype.Int4      `json:"year_of_publication"`
	CreatedAt         pgtype.Timestamp `json:"created_at"`
	UpdatedAt         pgtype.Timestamp `json:"updated_at"`
	Available         pgtype.Bool      `json:"available"`
	DeletedAt         pgtype.Timestamp `json:"deleted_at"`
}

type BorrowedBook struct {
	ID         int32            `json:"id"`
	BookID     int32            `json:"book_id"`
	UserID     int32            `json:"user_id"`
	BorrowedAt pgtype.Timestamp `json:"borrowed_at"`
	DueDate    pgtype.Timestamp `json:"due_date"`
	ReturnedAt pgtype.Timestamp `json:"returned_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Email     string           `json:"email"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	DeletedAt pgtype.Timestamp `json:"deleted_at"`
}
