FROM golang:1.26-alpine

# Install goose
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /migrations

# Copy migration files into the image
COPY db/migrations /migrations

ENTRYPOINT ["goose"]
