// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	DeleteBook(ctx context.Context, id int32) error
	GetBook(ctx context.Context, id int32) (Book, error)
	ListBooks(ctx context.Context) ([]Book, error)
	SearchBooksByAuthor(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error)
	SearchBooksByTitle(ctx context.Context, dollar_1 pgtype.Text) ([]Book, error)
	UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error)
}

var _ Querier = (*Queries)(nil)
