apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: bookstore
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: wait-for-postgres
        image: postgres:18-alpine
        env:
          - name: PGHOST
            value: postgres-service
          - name: PGPORT
            value: "5432"
          - name: PGUSER
            valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_USER } }
          - name: PGPASSWORD
            valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_PASSWORD } }
          - name: PGDATABASE
            valueFrom: { secretKeyRef: { name: postgres-secrets, key: POSTGRES_DB } }
        command: ["sh", "-c"]
        args:
          - |
            until pg_isready -h "$PGHOST" -p "$PGPORT" -U "$PGUSER" -d "$PGDATABASE"; do
            echo "Waiting for postgres..."
            sleep 2
            done
      containers:
        - name: migrate
          image: iedesnoek/bookstore-migrate:1.0.0
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: DATABASE_URL

          args:
            - -dir
            - /migrations
            - postgres
            - $(DATABASE_URL)
            - up